class DongerConstants
	HIGH_DEFENSE = "High Defense"
	BALANCED_DEFENSE = "Balanced Defense"
	LOW_DEFENSE = "Low Defense"

	HIGH_DIFFICULTY = "High Diffulty"
	BALANCED_DIFFICULTY = "Balanced Difficulty"
	LOW_DIFFICULTY = "Low Difficulty"

	HYBRID_DAMAGE = "Hybrid Damage"
	ABILITY_DAMAGE = "Ability Damage"
	ATTACK_DAMAGE = "Attack Damage"

	FIGHTER_ROLE = "Fighter"
	TANK_ROLE = "Tank"
	SUPPORT_ROLE = "Support"
	MAGE_ROLE = "Mage"
	MARKSMAN_ROLE = "Marksman"
	ASSASSIN_ROLE = "Assassin"

	SLOW = "Slow"
	STUN = "Stun"
	ROOT = "Root"
	SHIELD = "Shield"
	HEAL = "Heal"
	MOVEMENT = "Movement"
	HEALTH_DAMAGE = "Health Damage"
	ARMOR = "Armor"
	ATTACK_SPEED = "Attack Speed"
	SILENCE = "Silence"
	PASSIVE = "Passive"
	JUMP = "Jump"
	MARK = "Mark"
	DISPLACE = "Displace"
	POISON = "Poison"
	ZONE = "Zone"
	FIRES = "Fires"
	STACKS = "Stacks"
	MAGIC_RESIST = "Magic Resist"
	SUMMONS = "Summons"
	TRUE_DAMAGE = "True Damage"
end